language: python
# Versiones que se requieren del lenguaje a utilizar.
python:
  "3.7 dev"
# Esta línea contiene el bloque de instalación de los prerequisitos del proyecto.
install:
  -pip install -r requirements.txt
# En esta línea iran los scripts que se ejecutarán.
script:
  -pytest